language: cpp
compiler:
- gcc
- clang
install:
# Install gcc-multilib (fixed some errors)
- sudo apt-get update -qq
- sudo apt-get install gcc-multilib
# Download conan
- wget $CONAN_URL -O conan.deb
- sudo dpkg -i conan.deb
- rm conan.deb
# Adjust config and settings
- conan user lasote


script:
- python build.py
